title: "Macキーボードショートカット集"
summary: "Macを使ったショートカットコマンドをまとめたものです。"
topics: ["Mac", "ショートカット"] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - introduction #はじめに
  - file-delete # ファイルのゴミ箱を経由せずに削除する方法
